apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-secret-injector
  labels:
    app: csi-secret-injector
    app.kubernetes.io/name: csi-secret-injector
    app.kubernetes.io/instance: csi-secret-injector
    app.kubernetes.io/component: "controller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-secret-injector
      app.kubernetes.io/instance: csi-secret-injector
      app.kubernetes.io/component: "controller"
  template:
    metadata:
      labels:
        app: csi-secret-injector
        app.kubernetes.io/name: csi-secret-injector
        app.kubernetes.io/instance: csi-secret-injector
        app.kubernetes.io/component: "controller"
    spec:
      serviceAccountName: csi-secret-injector
      containers:
        - name: csi-secret-injector
          image: "csi-secret-injector"
          imagePullPolicy: IfNotPresent
          ports:
          - name: https
            containerPort: 8443
            protocol: TCP
---
