apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: csi-secret-injector-webhook
  labels:
    app: webhook
    app.kubernetes.io/name: csi-secret-injector
    app.kubernetes.io/instance: csi-secret-injector
    app.kubernetes.io/component: "webhook"
webhooks:
  - name: csi-secret-injector.webhook.xcxc.dev
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/component
          operator: NotIn
          values:
            - "controller"
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "v1"
        operations:
          - CREATE
        resources:
          - "pods"
    admissionReviewVersions: ["v1"]
    matchPolicy: Equivalent
    timeoutSeconds: 10
    failurePolicy: Ignore
    # FIXME: Actually have what may be considered sideEffects. Should be fixed.
    sideEffects: None
    clientConfig:
      service:
        name: csi-secret-injector
        namespace: "util"
        path: /mutate
      caBundle: ""
---
