apiVersion: v1
kind: Service
metadata:
  name: csi-secret-injector
  labels:
    app: csi-secret-injector
    app.kubernetes.io/name: csi-secret-injector
    app.kubernetes.io/instance: csi-secret-injector
    app.kubernetes.io/component: "controller"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    name: https
    targetPort: 8443
  selector:
    app.kubernetes.io/name: csi-secret-injector
    app.kubernetes.io/instance: csi-secret-injector
    app.kubernetes.io/component: "controller"
---
